// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSbJoNcI59uQl-M2e7cOOND4B4G8kvGvA',
    appId: '1:900705927891:web:da8157c76f4e493d7e8a26',
    messagingSenderId: '900705927891',
    projectId: 'poc-bateaux-flutter',
    authDomain: 'poc-bateaux-flutter.firebaseapp.com',
    storageBucket: 'poc-bateaux-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZNjQ1OukNjQlglA6uo3CgSZsAGgQgN_s',
    appId: '1:900705927891:android:d95d458d643e66a67e8a26',
    messagingSenderId: '900705927891',
    projectId: 'poc-bateaux-flutter',
    storageBucket: 'poc-bateaux-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn3xPnewn2tucVl4VIofVrERQMQe6gBQE',
    appId: '1:900705927891:ios:ae47bc15e2bab1387e8a26',
    messagingSenderId: '900705927891',
    projectId: 'poc-bateaux-flutter',
    storageBucket: 'poc-bateaux-flutter.firebasestorage.app',
    iosBundleId: 'com.example.pocGpsBateaux',
  );

}